### ISSUE TITLE
PSR-15 Support?

### ISSUE THREAD

**Issue by undercloud** [relayphp/Relay.Relay#32]
coming soon?

**Comment by GreatOwl** [comment]
Pipelines are not middleware! It is a different concept. However, pipelines would be a great tool for implementing a psr-15 compatible library, in my opinion!

**Comment by GreatOwl** [comment]
Sorry. Wrong library

**Comment by pmjones** [comment]
Hey @undercloud -- I have not been following the discussions too closely since (1) they attempted and failed to throw me out, then (2) re-constituted the group and I declined to re-join it.

Having said that, I understand the http-interop group is having their discussions mostly off-list. Are you keeping up with it? How close do they look to moving toward a finalized set of interfaces?

**Comment by undercloud** [comment]
To say the truth, no! I am developing a framework based on`psr7`, I first realized all based `relay` and `https: //github.com/oscarotero/psr7-middlevares`, but then learned about 15, it seems more refined and comfortable, and I need a tool to work it out.

**Comment by pmjones** [comment]
/me nods

I actually delayed Relay 2 on the basis of the PSR-15 work, and created a (perhaps temporary) lambda-style system called Telegraph. http://telegraphp.com/

When PSR-15 is done, if ever, I expect to roll Telegraph back into Relay as Relay 2.

**Comment by undercloud** [comment]
That's cool! I will check for updates.
