### ISSUE TITLE
Feature request - possibly add support for 'trampolining' 

### ISSUE THREAD

**Issue by far-blue** [relayphp/Relay.Relay#34]
Hello :)

One side-effect of middleware stacks seems to be very long exception stacks when something goes wrong. I heard a term 'trampolining' as a way to reduce this issue and thought it might be a good feature request. I think, basically, the technique unwinds the stack periodically. I guess this would mean a large change to the way middlewares are dispatched because you'd not be able to just call middleware A which then calls B which then calls C etc. Instead you'd have to use a loop or similar.

Something to ponder, maybe?

Robert

**Comment by kevinsmith** [comment]
I did a quick search but was unable to find more on this technique. Could you provide some links to discussions about this being used in the wild with pros/cons, etc?

**Comment by far-blue** [comment]
As a general technique it's used in many places - wikipedia covers the basics of the idea as part of the page on trampolining: https://en.wikipedia.org/wiki/Trampoline_(computing) (under high-level programming). It's used alongside 'Continuation-passing style' function optimisation in functional languages to cope with really deep stacks.

In general it means rather than A calling B calling C, A would need to return back out to a manager that would then call B and so on. In PHP this could possibly be done using generators and yield. The result is that the execution stack (and so the exception stack trace) are much shorter.

It was just a thought, anyhow :)

**Comment by cxj** [comment]
Interesting.  I was not familiar with all the formal nomenclature and theory with trampolining and continuation-passing style of programming, but it makes immediate sense.  I've at times written code like that just to reduce the stack depth of complexity for the purposes of understanding what is going on, and probably a couple of times just to reduce the stack memory being used (in a limited computing environment such as embedded systems or kernel device drivers, etc.).

I don't think we are at any kind of performance limitations in Relay and PHP, but it's absolutely true that the execution path through the fairly deep stack is a lot harder to understand for the programmer developing and debugging than most code I've dealt with.

So I rather like the idea of finding a way to trampoline Relay's processing.  It would certainly make Relay unique among its competitors!

**Comment by far-blue** [comment]
Although I initially thought maybe this could be done with generators I think maybe it won't be possible. The way a middleware calls 'next' and then expects a response means it wouldn't be possible to just wrap the middleware in a shim, as far as I can see. I think the middleware would have to know it was being used differently and do something like `$response = yield $request;` rather than the normal `$response = $next($request);`.

Maybe better brains than me could find a solution!

**Comment by kevinsmith** [comment]
Looks like an interesting suggestion, @far-blue! I can imagine an implementation, but I'm not sure I'm convinced of the benefits. As @cxj noted, we're not typically up against any performance limitations here, so the benefits there would be marginal.

Such a design would require Relay to "trick" each middleware into handing execution back to the runner, which would ironically make Relay less obvious in the way it works as far as PSR-15 runners go.  

And actually, since preceding middleware could modify the request/response, I'd argue you _do_ want to see those middleware in a stack trace while debugging.

**Comment by jasny** [comment]
> A trampoline simulates a tail call optimization by calling a function which might return another function (which will be called again) or a computed result. The trampoline will keep calling in a loop the returned function, and whenever the function returns a computed value instead of a function, the trampoline returns the value.

In other words; trampolining on works on tails calls, so when the response from the handler is directly returned and not used by the middleware. Also try/catch won't work when trampolining.

Example

```
function a ($req) {
  $reqA = $req->withAttribute('a', 1);
  return b($reqA);
}
function b ($req) {
  $reqB = $req->withAttribute('b', 1);
  return c($reqB);
}
function c ($req) {
  $ab = $req->getAttribute('a') + $req->getAttribute('b');
  return new Response($ab);
}

$res = a($req);
```

The normal flow is like

```
$res = (function ($req) {
  $reqA = $req->withAttribute('a', 1);

  return (function ($req) {
    $reqB = $req->withAttribute('b', 1);

    return (function ($req) {
      $ab = $req->getAttribute('a') + $req->getAttribute('b');
      return new Response($ab);
    })($reqB);
  })($reqA);
})($req);
```

With tail call optimization, only the arguments for the next called is kept, the rest is freed. This means you lose the depth (not the functions). So what happens is something like this;

```
$reqA = (function ($req) {
  $reqA = $req->withAttribute('a', 1);
  return $reqA;
})($req);

$reqB = (function ($req) {
  $reqB = $req->withAttribute('b', 1);
  return $reqB;
})($reqA); 

$res = (function ($req) {
  $ab = $req->getAttribute('a') + $req->getAttribute('b');
  return new Response($ab);
})($reqB);
```

This can be simulated with a trampoline by returning a `ServerRequest` instead of a `Response`. While this isn't allowed by the PSR interface, that can be overcome by wrapping the request in a response object.

I've made a proof of concept here: https://github.com/jasny/relay/blob/poc-trampoline/tests/example/trampoline.php

_P.S. While this is very cool and all, I'm not suggesting it's actually a good idea._

**Comment by kevinsmith** [comment]
Very cool proof of concept @jasny, thanks for sharing! But on the whole, I still don't see much real-world benefit to this kind of optimization in Relay. If anyone can share an example from an app in production where it would actually make a difference, I'd love to hear about it.

Until then, closing this issue to keep things tidy.
