### ISSUE TITLE
Callable Middleware Interface question

### ISSUE THREAD

**Issue by odan** [relayphp/Relay.Relay#39]
I don't understand why the middleware response looks like this?

```php
function (
    Request $request, // the request
    callable $next // the next middleware or handler
) : Response {
    // ...
}
```

How to get the response?

Should the interface not look more like this in PSR-15?

Example:

```php
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

class MyMiddleware
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $response = $handler->handle($request);

        // do something

        return $response;
    }
}
```

**Comment by kevinsmith** [comment]
I'm not sure I can find the thing you're referring to, @odan. Where are you seeing the code you pasted in the first example?

**Comment by odan** [comment]
@kevinsmith This example code is from: https://relayphp.com/

Screenshot:

![image](https://user-images.githubusercontent.com/781074/55560148-f0e19980-56ef-11e9-886f-3d0c9513ec67.png)

**Comment by kevinsmith** [comment]
Ah, gotcha. That's saying that Relay handles PSR-15 middleware, as the spec requires, but as an added feature it _also_ handles callable middleware.

The Request parameter and the Response return actually are PSR-7 objects (note the imports at the top), but callable middleware receives `callable` instead of `RequestHandlerInterface`.

Does that help clear it up?

**Comment by odan** [comment]
Ok thank you :+1:
