### ISSUE TITLE
2.x cryptic error on empty queue

### ISSUE THREAD

**Issue by urugator** [relayphp/Relay.Relay#42]
`new Relay([])->handle($request);`
results in 
` Uncaught Error: Function name must be a string`

https://github.com/relayphp/Relay.Relay/blob/2.x/src/Runner.php#L31
`$entry` becomes `false`

**Comment by niden** [comment]
From my understanding this appears because `$middleware` is `false`. When the queue is empty the last middleware is called like this

`$middleware($request, $this)`

There is no last or any middleware so this appears.

Look at the tests here: https://github.com/relayphp/Relay.Relay/blob/2.x/tests/RelayTest.php#L41
