### ISSUE TITLE
Allow to use the same instance multiple times

### ISSUE THREAD

**Issue by oscarotero** [relayphp/Relay.Relay#5]
Currently, the `__invoke()` method of `Relay` use `array_shift` to get the next middleware from the queue. I think it should better to use [next()](http://php.net/next) to get the element without remove it, so the queue should be used multiple times:

``` php
$dispatcher = new Relay([$middleware1, $middleware2]);

$response = $dispatcher(new ServerRequest(), new Response());
$response2 = $dispatcher(new ServerRequest(), new Response());
```

**Comment by pmjones** [comment]
I had considered something like that, but I was unable to imagine a use-case. The example you give shows that not-shifting allows reuse, but _why_ would one want to re-use it?

**Comment by oscarotero** [comment]
Well, I'm thinking in a http client executing the same operations in multiple requests (for example, to download files), or something like that.
BTW, I see `__invoke` accepts instances of `ServerRequestInterface` but not `RequestInterface`. What is the reason?

**Comment by pmjones** [comment]
> I see __invoke accepts instances of ServerRequestInterface but not RequestInterface. What is the reason?

That question gives me some insight into your thinking. I thought of Relay as something for the server-side, receiving client requests and then sending back responses. But your question makes me think you'd also like to use it when sending out requests and receiving responses. Is that right?

**Comment by oscarotero** [comment]
Yes, I think the middleware logic can be applied in both directions, so why limit to just one direction? :smiley:

**Comment by pmjones** [comment]
> why limit to just one direction?

No good reason, other than I didn't think of it. Feature request accepted!

**Comment by oscarotero** [comment]
Great! :+1:

**Comment by pmjones** [comment]
@oscarotero I have pushed a new branch with reusable Relay instances at https://github.com/relayphp/Relay.Relay/tree/reusable. Look it over and tell me what you think.

In building this, I have come to think that inbound request handling to generate a response (the "current" use case) is not quite the same as generating a request to get back a response (the "new" use case). As @mtdowling has opined elsewhere, passing along a response object from the very beginning may not really be necessary here. One would expect the tail-end middleware, or perhaps an intervening one, to send the request and return the resulting response object, rather than passing along a response object from the very beginning. That implies to me a modified middleware signature for client-like outbound requests, perhaps `function ($request, $next)` and `return $response`. As for how to handle early exits or failure modes, I don't know.

Thoughts?

**Comment by pmjones** [comment]
p.s. One would might need a $response object if $next expects to modify the returned response, but I have a hard time imagining that kind of thing in an "outbound request / returned response" scenario.

**Comment by oscarotero** [comment]
Hi. The new code looks great. Perhaps the api would be simplified passing the queue to the constructor directly instead of a RunnerFactory, or creating a static method `Relay::create(array $queue, $resolver)` to ease the instantation, but it really is not important.

And about the "new" use case, IMHO I don't think the api should change. The http client sending out requests and receiving responses was just an example. But there are other examples such a [reactphp like application](https://github.com/reactphp/react#usage), unit testing with different requests and the same middleware queue, etc. I think all middlewares should have the same arguments, because they can be used in different cases. For example, a middleware to execute gzip compression to the body of the request, can be used in a traditional serverRequest => response and in a http client. So if all middlewares share the same interface they are more interchangeable.

**Comment by pmjones** [comment]
/me nods

So the concentration should still be on "ServerRequest" and server-side stuff; if people want to use it for making client requests, that's their problem. ;-)

Yes? If so, I'll add a couple more mods, then merge it.

**Comment by oscarotero** [comment]
Yes, I think it's the best. :+1:

**Comment by pmjones** [comment]
@oscarotero Your request is granted; cf. the newest 1.x pushes.
